services:
  antlr:
    image: uhnpybara/antlr:1113
    ports:
      - "8081:8081"
    volumes:
      - ../data:/app/data
    environment:
      PLSQL_DIR: /app/data/plsql
      ANALYSIS_DIR: /app/data/analysis